### ISSUE TITLE
Hunter beast training and enchanting tab mixed up

### ISSUE THREAD

**Issue by rozsabenjamin** [leatrix/leatrix-plus-bcc#71]
Enchanting tab's certain elements are shifted away from their original place, while somehow Beast Training's certain elements got mixed into the same panel.
I narrowed this down to LTP's "Enhance Professions" setting.
My other profession is Tailoring, oddly that one looks ok. Can't tell for the rest of the professions.

Thoughts? :)

![image](https://user-images.githubusercontent.com/95718915/145103321-c2fbd66a-0b55-40bb-a420-061166a4685f.png)

**Comment by leatrix** [comment]
This is caused by TradeSkillMaster.  I know you are using the default UI for profession windows but TradeSkillMaster is still running in the background.  If you disable TradeSkillMaster, the problem should be fixed.  You should report this to the developers of TradeSkillMaster.  It's nothing to do with Leatrix Plus and still happens with Leatrix Plus disabled.

Steps to reproduce:
- Open enchanting window.  It opens fine.
- Now open beast training window without closing enchanting window.  It opens fine.
- Now try to open enchanting window again (without closing beast training).  It doesn't open.  You have to click the enchanting button a further two times to get the window to open.

The same issue can also cause two profession windows to get blended together.

**Comment by rozsabenjamin** [comment]
I suspected TSM too initially, but the issue persists after TSM disabled - the only way I managed to get rid of this was disabling "Enhance Professions" in LTP or disabling LTP itself :(

**Comment by leatrix** [comment]
My apologies.  I did notice that the craft frame filter dropdown wasn't being positioned (at all) by 'Enhance professions' (as shown in your screenshot).

However, training points being shown in profession frames is a bug in the default UI and occurs without any addons enabled.

Please try 2.5.73.alpha.7.  The filter dropdown should be positioned correctly and training points should no longer show in profession frames.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

**Comment by rozsabenjamin** [comment]
worked like a charm, thank you so much!
